---
- name: Install lemonade all in one
  hosts: lemonade
  become: yes
  roles:
    - { role:  "lemonade", tags: ['lemonade'] }
  vars:
    citron: true
    thorn: true
    lemonade_thorn_host: "http://{{ groups['lemonade'][0] }}:3000"
    lemonade_citron_host: "http://{{ groups['lemonade'][0] }}"
