---
- include: lemonade_pre_install.yml

- name: Clone citron git repositories
  git:
    repo: "{{ lemonade_citron_git_repo }}"
    dest: "{{ lemonade_system_user_home }}/cloned-repos/lemonade-citron"
    version: "{{ lemonade_citron_git_branch }}"
    depth: 1
    force: yes
  ignore_errors: yes
  tags:
    - lemonade-clone-repos
    - lemonade-install
  become: no

- include: npm_modules_setup.yml

- name: Install citron npm modules
  npm:
    path: "{{ lemonade_system_user_home }}/cloned-repos/lemonade-citron"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  become: no
  tags:
    - lemonade-citron-npm-modules-install

- name: Install bower packages
  bower:
    path: "{{ lemonade_system_user_home }}/cloned-repos/lemonade-citron"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  become: no
  tags:
    - lemonade-citron-install
    - lemonade-citron-bower-modules-install

- name: Setup Nginx
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts_filename: citron.conf
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: 80
        index: index.html
        root: "/usr/share/nginx/html"
        extra_parameters: |
          location / {
            try_files $uri $uri/ /index.html;
          }
  tags:
    - lemonade-citron-nginx-install

- name: Create ember dotenv production
  copy:
    content:  "THORN=http://localhost:3000"
    dest: "{{ lemonade_system_user_home }}/cloned-repos/lemonade-citron/.env"
    force: yes
  become: no
  tags:
    - lemonade-citron-build

- name: Build ember app
  command: "ember build -prod --output-path=/usr/share/nginx/html"
  args:
    chdir: "{{ lemonade_system_user_home }}/cloned-repos/lemonade-citron"
  register: citron_build
  tags:
    - lemonade-citron-build
    - lemonade-citron-install
