---
- include: lemonade_pre_install.yml

- name: Clone citron git repositories
  git:
    repo: "{{ lemonade_citron_git_repo }}"
    dest: "{{ lemonade_system_user_home }}/citron"
    version: "{{ lemonade_citron_git_branch }}"
    depth: 1
    force: yes
  ignore_errors: yes
  tags:
    - lemonade-git-repository
    - lemonade-citron-git-repository

- include: npm_modules_setup.yml
  tags:
    - lemonade-citron-js
    - lemonade-citron-nodejs

- name: Install citron npm modules
  npm:
    path: "{{ lemonade_system_user_home }}/citron"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - lemonade-citron-js
    - lemonade-citron-js-modules

- name: Install bower packages
  bower:
    path: "{{ lemonade_system_user_home }}/citron"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - lemonade-citron-js
    - lemonade-citron-js-modules

- name: Create ember dotenv production
  copy:
    content:  "THORN={{ lemonade_thorn_host }}"
    dest: "{{ lemonade_system_user_home }}/citron/.env"
    force: yes
  tags:
    - lemonade-ember
    - lemonade-citron-ember

- name: Build ember app
  command: "ember build -prod --output-path=/usr/share/nginx/html"
  args:
    chdir: "{{ lemonade_system_user_home }}/citron"
  register: citron_build
  tags:
    - lemonade-ember
    - lemonade-citron-ember

- name: Chown directory
  file:
    path: "{{ lemonade_system_user_home }}/citron"
    state: directory
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    mode: 0755
    recurse: true
  tags:
    - lemonade-dirs

- name: Setup Nginx
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts_filename: citron.conf
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: 80
        index: index.html
        root: "/usr/share/nginx/html"
        extra_parameters: |
          location / {
            try_files $uri $uri/ /index.html;
          }
  tags:
    - lemonade-nginx
    - lemonade-citron-nginx
    - lemonade-services
