---
- name: Create the system groups
  group:
    name: "{{ lemonade_system_group }}"
    state: present
    system: yes
  tags:
    - system-groups

- name: Create system users
  user:
    name: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    comment: "{{ lemonade_system_comment }}"
    shell: "{{ lemonade_system_shell }}"
    system: yes
    createhome: yes
    home: "{{ lemonade_system_user_home }}"
  tags:
    - system-users

- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    mode: 0755
  with_items:
    -  /var/run/lemonade
    -  /var/log/lemonade
    -  "{{ lemonade_system_user_home }}"
  tags:
    - lemonade-dirs

- name: Ensure host on hosts file
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
  tags:
    - lemonade-hosts

- name: 'apt | update'
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - lemonade-apt
    - lemonade-apt-update

- name: Install common apt packages
  apt:
    pkg: "{{ item }}"
  with_items: "{{ lemonade_apt_packages }}"
  tags:
    - lemonade-apt

