---
- name: Create the system groups
  group:
    name: "{{ item }}"
    state: "present"
    system: "yes"
  with_items:
    - "{{ lemonade_system_group }}"
  tags:
    - system-groups

- name: Create system users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    comment: "{{ item.comment }}"
    shell: "{{ lemonade_system_shell }}"
    system: "yes"
    createhome: "{{ item.createhome }}"
    home: "{{ lemonade_system_user_home }}"
  with_items:
    - name: "{{ lemonade_system_user }}"
      group: "{{ lemonade_system_group }}"
      comment: "{{ lemonade_system_comment }}"
      createhome: "yes"
  tags:
    - system-users

- name: Create dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(lemonade_system_user) }}"
    group: "{{ item.group|default(lemonade_system_group) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/opt", mode: "0755", owner: "root", group: "root" }
    - { path: "/var/log/lemonade",  owner: "root"}
    - { path: "{{ lemonade_system_user_home }}" }
    - { path: "{{ lemonade_system_user_home }}/venvs", mode: "0755", owner: "root", group: "root" }
    - { path: "{{ lemonade_system_user_home }}/cloned-repos", mode: "0755", owner: "root", group: "root" }
  tags:
    - lemonade-dirs

- name: Ensure host on hosts file
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
  tags:
    - lemonade-hosts

- name: 'apt | update'
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - apt-update

- name: Install common apt packages
  apt:
    pkg: "{{ item }}"
  with_items: "{{ lemonade_apt_packages }}"
  tags:
    - lemonade-apt-commong-packages

