- include: lemonade_pre_install.yml

- name: Clone limonero git repositories
  git:
    dest: "{{ lemonade_system_user_home }}/cloned-repos/limonero"
    repo: "{{ lemonade_limonero_git_repo }}"
    version: "{{ lemonade_limonero_git_branch }}"
    depth: 1
    force: yes
  ignore_errors: yes
  tags:
    - lemonade-clone-repos
    - lemonade-install
  become: no

- include: pip_packages_setup.yml
  vars:
    lemonade_project: limonero

- name: Create systemd service unit
  template:
    src: python.service.j2
    dest: /etc/systemd/system/limonero.service
    owner: root
    group: root
    force: yes
  vars:
    lemonade_project: limonero
    lemonade_project_workdir: "{{ lemonade_system_user_home }}/cloned-repos/limonero"
    python_app: "./limonero/app_api.py -c stand.json"
  tags:
    - lemonade-limonero-service
    - lemonade-limonero-systemd

- name: Create app config
  template:
    src: limonero.json.j2
    dest: "{{ lemonade_system_user_home }}/cloned-repos/limonero/stand.json"
    force: yes
  tags:
    - lemonade-limonero-service
    - lemonade-limonero-service-systemd

- name: Install MySQL
  include_role:
    name: "geerlingguy.mysql"
  vars:
    mysql_databases:
      - name: limonero
    mysql_users:
      - name: "{{ lemonade_limonero_db_user }}"
        host: "%"
        password: "{{ lemonade_limonero_db_passwd }}"
        priv: "{{ lemonade_limonero_db_user }}.*:ALL"
  tags:
    - lemonade-limonero-mysql-install

- name: Run limonero service
  systemd:
    name: limonero
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: service_started
  until: service_started|success
  retries: 3
  delay: 3
  tags:
    - lemonade-limonero-service
