---
- name: Install node, npm packages
  apt:
    pkg: "{{ item }}"
  with_items:
    - nodejs
    - npm
  tags:
    - lemonade-citron-install
    - lemonade-node-npm-install

- name: Create node link
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node owner=root group=root state=link
  tags:
    - lemonade-citron-install
    - lemonade-node-npm-install

- name: Install global npm modules
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - "bower"
    - "ember-cli"
  tags:
    - lemonade-citron-install
    - lemonade-node-npm-install
    - lemonade-npm-modules-install
