- name: Install pip and virtualenv
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-pip
    - virtualenv
    - libmysqlclient-dev
  tags:
    - lemonade-pip
    - lemonade-apt

- name: Create lemonade virtualenvs
  command: "virtualenv {{ lemonade_system_user_home }}/{{ lemonade_project }}"
  tags:
    - lemonade-virtualenv

- name: Ensure lemonade group on venv
  file:
    dest: "{{ lemonade_system_user_home }}/{{ lemonade_project }}"
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    recurse: yes
  tags:
    - lemonade-virtualenv

- name: Install pip packages (venv)
  pip:
    state: present
    virtualenv: "{{ lemonade_system_user_home }}/{{ lemonade_project }}"
    requirements: "{{ lemonade_system_user_home }}/{{ lemonade_project }}/requirements.txt"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - lemonade-pip
    - lemonade-virtualenv
