
- name: Create lemonade venv dirs
  file:
    path: "/opt/venvs/lemonade-{{ item }}"
    state: directory
    owner: "root"
    group: "{{ lemonade_system_group }}"
    mode: "0775"
  with_items: "{{ lemonade_pip_projects }}"
  tags:
    - lemonade-venv-dirs

- name: Create lemonade virtualenvs
  command: "virtualenv /opt/venvs/lemonade-{{ item }}"
  args:
    creates: "/opt/venvs/lemonade-{{ item }}/bin"
  with_items: "{{ lemonade_pip_projects }}"
  tags:
    - lemonade-install
    - lemonade-create-venv

- name: Ensure lemonade group on venv
  file:
    dest: "/opt/venvs/lemonade-{{ item }}"
    owner: "root"
    group: "lemonade"
    recurse: "yes"
  with_items: "{{ lemonade_pip_projects }}"
  tags:
    - lemonade-install
    - lemonade-create-venv

- name: Install pip packages (venv)
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "/opt/venvs/lemonade-{{item}}"
    requirements: "/opt/cloned-repos/lemonade-{{ item }}/requirements.txt"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ lemonade_pip_projects }}"
  tags:
    - lemonade-install
    - lemonade-pip-packages

