- name: Install pip and virtualenv
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-pip
    - virtualenv
    - libmysqlclient-dev
  tags:
    - lemonade-tahiti-install
    - lemonade-apt-install

- name: Create lemonade virtualenvs
  command: "virtualenv {{ lemonade_system_user_home }}/cloned-repos/{{ lemonade_project }}"
  become: no
  tags:
    - lemonade-install
    - lemonade-create-venv

- name: Ensure lemonade group on venv
  file:
    dest: "{{ lemonade_system_user_home }}/cloned-repos/{{ lemonade_project }}"
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    recurse: yes
  tags:
    - lemonade-install
    - lemonade-create-venv

- name: Install pip packages (venv)
  pip:
    state: present
    virtualenv: "{{ lemonade_system_user_home }}/cloned-repos/{{ lemonade_project }}"
    requirements: "{{ lemonade_system_user_home }}/cloned-repos/{{ lemonade_project }}/requirements.txt"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  become: no
  tags:
    - lemonade-install
    - lemonade-pip-packages

