---
- name: Install gems dependencies
  apt:
    pkg: "{{ item }}"
  with_items:
    - libmysqlclient-dev
  tags:
    - lemonade-apt

- name: Ruby with Rbenv install
  include_role:
    name: "spitfast.rbenv"
  vars:
    rbenv_ruby_version: 2.3.1
    rbenv_user: "{{ lemonade_system_user }}"
    rbenv_root_path: "{{ lemonade_system_user_home }}/.rbenv"
  tags:
    - lemonade-ruby
    - lemonade-rbenv

- name: Install thorn gems
  bundler:
    chdir: "{{ lemonade_system_user_home }}/thorn"
    state: present
    user_install: yes
    executable: "{{ lemonade_system_user_home }}/.rbenv/shims/bundle"
  become: no
  tags:
    - lemonade-ruby
    - lemonade-gems
