- include: lemonade_pre_install.yml

- name: Clone stand git repositories
  git:
    dest: "{{ lemonade_system_user_home }}/stand"
    repo: "{{ lemonade_stand_git_repo }}"
    version: "{{ lemonade_stand_git_branch }}"
    depth: 1
    force: yes
  ignore_errors: yes
  tags:
    - lemonade-git-repository
    - lemonade-stand-git-repository

- include: pip_packages_setup.yml
  vars:
    lemonade_project: stand

- name: Create systemd service unit
  template:
    src: python.service.j2
    dest: /etc/systemd/system/stand.service
    owner: root
    group: root
    force: yes
  vars:
    lemonade_project: stand
    lemonade_project_workdir: "{{ lemonade_system_user_home }}/stand"
    python_app: "./stand/app_api.py -c stand.json"
  tags:
    - lemonade-systemd
    - lemonade-stand-systemd

- name: Create app config
  template:
    src: stand.json.j2
    dest: "{{ lemonade_system_user_home }}/stand/stand.json"
    force: yes
  vars:
    lemonade_tahiti_authtoken: l3m0n4d1
  tags:
    - lemonade-stand-config

- name: Install MySQL
  include_role:
    name: "geerlingguy.mysql"
  vars:
    mysql_databases:
      - name: stand
    mysql_users:
      - name: "{{ lemonade_stand_db_user }}"
        host: "%"
        password: "{{ lemonade_stand_db_passwd }}"
        priv: "{{ lemonade_stand_db_user }}.*:ALL"
  tags:
    - lemonade-mysql
    - lemonade-stand-mysql

- name: Install Redis
  include_role:
    name: geerlingguy.redis
  tags:
    - lemonade-redis
    - lemonade-stand-redis

- name: Chown directory
  file:
    path: "{{ lemonade_system_user_home }}/stand"
    state: directory
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    mode: 0755
  tags:
    - lemonade-dirs

- name: Run stand service
  systemd:
    name: stand
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: service_started
  until: service_started|success
  retries: 3
  delay: 3
  tags:
    - lemonade-systemd
    - lemonade-stand-systemd
