---
- include: lemonade_pre_install.yml

- name: Clone thorn git repositories
  git:
    repo: "{{ lemonade_thorn_git_repo }}"
    dest: "{{ lemonade_system_user_home }}/thorn"
    version: "{{ lemonade_thorn_git_branch }}"
    depth: 1
    force: yes
  ignore_errors: yes
  tags:
    - lemonade-git-repository
    - lemonade-thorn-git-repository

- include: ruby_gems_install.yml

- name: Install MySQL
  include_role:
    name: "geerlingguy.mysql"
  vars:
    mysql_databases:
      - name: thorn
    mysql_users:
      - name: "{{ lemonade_thorn_db_user }}"
        host: "%"
        password: "{{ lemonade_thorn_db_passwd }}"
        priv: "{{ lemonade_thorn_db_user }}.*:ALL"
  tags:
    - lemonade-mysql
    - lemonade-thorn-mysql

- name: Copy rails database config
  template:
    src:  database.yml.j2
    dest: "{{ lemonade_system_user_home }}/thorn/config/database.yml"
    force: yes
  tags:
    - lemonade-rails
    - lemonade-thorn-config

- name: Chown directory
  file:
    path: "{{ lemonade_system_user_home }}/thorn"
    state: directory
    owner: "{{ lemonade_system_user }}"
    group: "{{ lemonade_system_group }}"
    mode: 0755
    recurse: true
  tags:
    - lemonade-dirs

- name: Setup database
  command: "{{ lemonade_system_user_home }}/.rbenv/shims/rake db:setup"
  args:
    chdir: "{{ lemonade_system_user_home }}/thorn"
  environment:
    RAILS_ENV: production
  run_once: true
  ignore_errors: yes
  register: rake_db_setup
  tags:
    - lemonade-rails
    - lemonade-thorn-config

- name: Rake db:setup failed
  fail: msg="Rake db:setup failed"
  when: "not 'already exists' in rake_db_setup.stderr"

- name: Run rails migrations and compile assets
  command: "{{ lemonade_system_user_home }}/.rbenv/shims/rake db:migrate"
  args:
    chdir: "{{ lemonade_system_user_home }}/thorn"
  environment:
    RAILS_ENV: production
  tags:
    - lemonade-rails
    - lemonade-thorn-config

- include: unicorn.yml
  tags:
    - lemonade-thorn-unicorn

- name: Setup Nginx
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts_filename: thorn.conf
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: 3000
        root: "{{ lemonade_system_user_home }}/thorn"
        extra_parameters: |
          try_files $uri/index.html $uri @thorn;
          location @thorn {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_pass http://thorn;
          }
    nginx_upstreams:
      - name: thorn
        servers:
          - "unix:/var/run/lemonade/thorn.sock fail_timeout=0"
  tags:
    - lemonade-nginx
    - lemonade-thorn-nginx

